### ISSUE TITLE
Single pages (not posts) show "READ OTHER POSTS"

### ISSUE THREAD

**Issue by willstocks** [panr/hugo-theme-terminal#129]
Is there a clean/correct way to remove the "READ OTHER POSTS" pagination at the bottom of each page?

I want it there when there are actual posts, but for pages that aren't listing posts it doesn't make much sense.

At the moment I have an `/about` and `/contact` page - both of which have READ OTHER POSTS at the bottom and clicking the arrow navigates you between those two pages.

I have the following in my `config.toml`:
```toml
[languages.en.menu]
  [[languages.en.menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
  [[languages.en.menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
``` 

And the file hierarchy is:
  `/content/about/index.md`
  `/content/contact/index.md`
