### ISSUE TITLE
Question: Why did you move back to webpack?

### ISSUE THREAD

**Issue by sophiabrandt** [panr/hugo-theme-terminal#199]
Hi @panr !
I have received several compliments for using your theme on your blog.

A while ago you moved to hugo pipelines. The great thing about that is that I could easily add a custom color scheme and custom favicon by creating two separate files (`assets/css/color/nord.css` and `static/img/favicon/nord.png`):
For example, my `assets/css/color/nord.css` file:
```css
@import '../main.css';
@import '../header.css';
@import '../logo.css';
@import '../pagination.css';
@import '../post.css';
@import '../syntax.css';
@import '../variables.css';

:root {
  --accent: #88C0D0;
  --background: color-mod(var(--accent) blend(#1D1E28 98%));
  --color: white;
  --border-color: rgba(255, 255, 255, .1);
}
```
Then, in `config.toml`, I just added the theme color:
```toml
  themeColor = "nord"
```
and everything worked fine.

Then, with commit https://github.com/panr/hugo-theme-terminal/commit/a6f223f522e53489afb7ffa9c89267a82bbcbe82 you moved back to webpack.

For my use case, the Hugo pipelines were superior, so I'm curious on why you moved back to webpack.

Is there a chance to either move back to the pipelines _or_ make it easier to use custom themes (like it was possible with the Hugo pipelines)?

Thank you for your work on this theme!
