### ISSUE TITLE
enableGitInfo not working/ updated at not working on posts

### ISSUE THREAD

**Issue by RafaelMoreira1180778** [panr/hugo-theme-terminal#348]
I am using this theme and I have the following config on my `config.toml`:
```toml
languageCode = "en-us"
theme = "terminal"
paginate = 5
enableGitInfo = true

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 2
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true
  autoCover = true
  showLastUpdated = true
  updatedDatePrefix = "Updated"
  Toc = true
  TocTitle = "echo \"Table of Contents\""
```
Then I created a post under `content/posts/test/index.md`:
```maarkdown
---
title: "Hello Friend"
date: "2022-06-29"
author: "Rafael Moreira"
cover: "hello.jpg"
description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec interdum metus. Aenean rutrum ligula sodales ex auctor, sed tempus dui mollis. Curabitur ipsum dui, aliquet nec commodo at, tristique eget ante."
---

...
```
I am saving and commiting the post but the created at and the updated at date are the same:
![image](https://user-images.githubusercontent.com/44571058/177055728-e24d993a-3e28-4348-9443-72aa31fdca59.png)
What should I do to enable this feature?
