### ISSUE TITLE
Change base font color

### ISSUE THREAD

**Issue by Umbragloom** [panr/hugo-theme-terminal#378]
I would like to change my base font color from white to something else. I have a styles.css in /static that I'm using to change my theme's background color. 

Can I just add a CSS reference for the body to change this color, or do I need to change it in the themes' CSS files?

**Comment by Umbragloom** [comment]
Nevermind, clearly been a long day. 

```css
 : root {                                                                         
    --accent: #bd00ff;                                                            
     --color: #b2ffe2;                                                             
   }  
                                                                                                                                                                                                                          
  .post-meta {                                                                    
                                                                                
  color: #00ff9f;                                                                   
  } 
```

adding the ```--color``` tag above changed the font color on the site as intended.
