### ISSUE TITLE
themeColor is ignored in last update

### ISSUE THREAD

**Issue by mpostument** [panr/hugo-theme-terminal#385]
Hello, my website used blue color for a long time, yesterday I updated the theme code to the latest version (using submodule) and my site was deployed with orange color. But the site is always orange

Link to website https://mpostument.com/. 

My config.toml

```toml
baseurl = "https://mpostument.com"
languageCode = "en-us"
theme = "terminal"
paginate = 5
title = "mpostument.com"
enableRobotsTXT = true

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "post"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "blue"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 4

  # show selector to switch language
  showLanguageSelector = true

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # whether to show a page's estimated reading time
  readingTime = true # default

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  Toc = false # default

  # set title for the table of contents
  # can be overridden in a page's front-matter
  TocTitle = "Table of Contents" # default

[permalinks]
  post = "/:year/:month/:day/:filename/"
```
