### ISSUE TITLE
Can't add icons to the main menu

### ISSUE THREAD

**Issue by EmilyGraceSeville7cf** [panr/hugo-theme-terminal#454]
This:

```yaml
menu:
  main:
  - identifier: about
    name: About
    url: /about/
    weight: 1
    pre: <i class="fa-solid fa-code"></i>
```

doesn't work. [There](https://github.com/command-line-interface-pages/site.github.io/blob/main/config.yaml) is config for my site.
