### ISSUE TITLE
`themeColor` does not work as expected

### ISSUE THREAD

**Issue by aperture147** [panr/hugo-theme-terminal#479]
No mater what color I try, `themeColor` are always be a yellowish accent. I'm using `hugo v0.134.0+extended`. My blog was deployed on Cloudflare Pages at [https://blog.haivq.com](https://blog.haivq.com). Tested on both local and Cloudflare.

My blog repository: [haivq/blog](https://github.com/haivq/blog)
My config.toml file:

```toml
baseurl = "https://blog.haivq.com/"

title = "Góc của Aperture"

theme = "terminal"
enableRobotsTXT = true

languageCode = "vi-VN"
defaultContentLanguage = "vi"

enableGitInfo = true
copyright = "© Aperture Prometheus :: 2018 - 2024"

[pagination]
  pagerSize = 5

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "blue"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "common/orange.png"

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = true
  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  updatedDatePrefix = "Cập nhật"

  readingTime = true
  autoCover = true
  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false

  framed = true

[languages]
  [languages.vi.params]
    languageName = "Tiếng Việt"
    title = "Góc của Aperture"
    subtitle = "Nơi ghi chép kinh nghiệm làm việc của tôi"
    owner = "Aperture Prometheus"
    keywords = "devops,coding,resume,experience"
    copyright = "Aperture Prometheus"
    menuMore = "Xem thêm"
    readMore = "Đọc tiếp"
    newerPosts = "Bài mới hơn"
    olderPosts = "Bài cũ hơn"
    readOtherPosts = "Xem tiếp"
    missingContentMessage = "Không tìm thấy trang..."
    missingBackButtonLabel = "Về trang chủ"
    minuteReadingTime = "phút đọc"
    words = "chữ"

    [languages.vi.params.logo]
      logoText = "Góc của Aperture"
      logoHomeLink = "/"
    [languages.vi.author]
      name = "Aperture"
      email = "me@haivq.com"
    [languages.vi.menu]
      [[languages.vi.menu.main]]
        identifier = "rss"
        name = "RSS"
        url = "/index.xml"
      [[languages.vi.menu.main]]
        identifier = "about"
        name = "Thông tin"
        url = "/about"
      [[languages.vi.menu.main]]
        identifier = "thoughts"
        name = "Suy nghĩ của tôi"
        url = "https://thoughts.haivq.com"
      

[markup.goldmark.renderer]
  unsafe = true

[services]
  [services.disqus]
    shortname = 'apertureprometheus'

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.youtube]
    disable = true
```
