### ISSUE TITLE
Feature Request: Customizable date/timestamps

### ISSUE THREAD

**Issue by KatieTheDev** [panr/hugo-theme-terminal#493]
Hi all,

While trying to customize my page to my liking, I discovered that Hugo has built-in support for different date and time formats. I would like to suggest a new feature where we can set if a timestamp should be shown or only date. I have a proof of concept available in my [website's repository](https://github.com/KatieTheDev/katiethe.dev/blob/main/layouts/_default/single.html). I believe that using some if-statements and adding some options to the main config file, that we should be able to add this as a feature.

If the community finds interest in this, I would be more than happy to start work on a PR.

**Comment by KatieTheDev** [comment]
![image](https://github.com/user-attachments/assets/6088f280-7395-4b1b-8ee9-8a9dfaaa518f)
This is an example of it working in action with how I currently have it set up.

**Comment by KatieTheDev** [comment]
In issue #477 another user has suggested replacing the `{{- .Date.Format "2006-01-02" -}}` string with a time.Format :date_medium string. I would be interested in incorporating this into a potential PR, though I am unsure if it would be better with it separate.

**Comment by KatieTheDev** [comment]
I should add that under my implementation, extra CSS is required to make it look how I did. In order to make the AM/PM designation uppercase, I created the following CSS rule:
```css
.post-time {
  text-transform: uppercase;
  padding: 0px;
  margin: 0px;
  border: 0px;
}
```
In order to fix the issue of the extra span created for .post-time, I added the following css as well:
```css
.post-time {
  text-transform: uppercase;
  padding: 0px;
  margin: 0px;
  border: 0px;
}
```
All of this can be found in my /assets/css/style.css file in my website's repository.
