### ISSUE TITLE
The css file should contain the word-wrap

### ISSUE THREAD

**Issue by 0031400** [panr/hugo-theme-terminal#558]
![Image](https://github.com/user-attachments/assets/2c2b5639-971c-4de0-ac41-06b28c048d38)
This is my site on the phone.  
My link is very long,but the `p` don't wrap.
I think we shoud add this to `themes\hugo-theme-terminal\assets\css\post.css`  
from
```css
.post-content {
  margin-top: 25px;
}
```
to
```css
.post-content {
  margin-top: 25px;
  word-wrap: break-word;
}
```
![Image](https://github.com/user-attachments/assets/8feb0a2a-5487-473b-afc0-7e1d0bc3b5ed)
After that,it looks good.
